### PR TITLE
Replace the deprecated Access Reviews endpoint

### LINKED ISSUE #49: The accessReviews endpoint is deprecated
The requests for accessReviews started returning an error:
```
Line |
 116 |  …  $results = Invoke-MgGraphRequest -Method GET -Uri $uriQueryEndpointF …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | GET https://graph.microsoft.com/beta/accessReviews?$filter=(businessFlowTemplateId+eq+%27832169fe-e1b7-4ce9-98b6-6a8db52eec6b%27) HTTP/1.1 403 Forbidden Transfer-Encoding: chunked Vary: Accept-Encoding Strict-Transport-Security: max-age=31536000
     | request-id: ff479254-14a6-4c3c-9788-9cf650faedad client-request-id: 0caa3695-534d-4433-bb78-5a34fc5cd217 x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"Sweden Central","Slice":"E","Ring":"5","ScaleUnit":"001","RoleInstance":"GV2PEPF00000EB1"}} Date: Thu,
     | 17 Aug 2023 08:09:37 GMT Content-Type: application/json Content-Encoding: gzip  {"error":{"code":"","message":"Attempted to perform an unauthorized
     | operation.","innerError":{"date":"2023-08-17T08:09:38","request-id":"ff479254-14a6-4c3c-9788-9cf650faedad","client-request-id":0caa3695-534d-4433-bb78-5a34fc5cd217"}}}
    7fbc901b-efe1-4c72-8ae6-99cb80b582de
```

The reason seems to be that this endpoint is deprecated and a replacement exists:

> This version of the access review API is deprecated and will stop returning data on May 19, 2023. Please use [access reviews API](https://learn.microsoft.com/en-us/graph/api/resources/accessreviewsv2-overview?view=graph-rest-beta&preserve-view=true).

https://learn.microsoft.com/en-us/graph/api/accessreview-list?view=graph-rest-beta&tabs=http#code-try-1

### PR DESCRIPTION
**Pull request by mathias-nyman**
The endpoint that was used up until now has been deprecated and no longer returns any data (returns 403):

> This version of the access review API is deprecated and will stop returning data on May 19, 2023. Please use access reviews API.
https://learn.microsoft.com/en-us/graph/api/accessreview-list?view=graph-rest-beta&tabs=http#code-try-1

Closes #49

### CODE REVIEW

**Comment by merill** [comment]
@mathias-nyman Thanks for the PR. Can you accept the CLA agreement so I can merge this in? Tx

**Comment by mathias-nyman** [comment]
@microsoft-github-policy-service agree company="RELEX Solutions"

**Comment by mathias-nyman** [comment]
@merill thanks for the rapid turnaround!

**Comment by merill** [comment]
Thank your for the PR :) @mathias-nyman 

The updated module has been published. Can you please test it out? Tx.

**Comment by mathias-nyman** [comment]
I can confirm that the latest AzureAdExporter module on PSGallery, version '1.0.1156034', works as expected. Thanks @merill!

**Comment by mathias-nyman** [comment]
@merill I want to terminate the CLA, but the commands for the github policy service don't seem to work. Can you check that you've set it up correctly for this repository? You'll find more details here:
https://github.com/microsoft/ContributorLicenseAgreement#terminating

**Pull request merged**
